services:
  db:
    image: postgres:15-alpine
    container_name: helden-online-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helden-online-django
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
