# Generated by Django 6.0 on 2026-05-23 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_message_deleted_by_recipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(max_length=120)),
                ('culture', models.CharField(max_length=120)),
                ('courage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sagacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('intuition', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('charisma', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dexterity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('agility', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('constitution', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('strength', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
