# Generated by Codex on 2026-05-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_herogroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroGroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_group_invitations', to='web.character')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='web.herogroup')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_hero_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_group_invitation', to='web.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroGroupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_participations', to='web.character')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='web.herogroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_group_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['character__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='herogroupinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('group', 'invited_user'), name='unique_pending_invitation_per_user_group'),
        ),
        migrations.AddConstraint(
            model_name='herogroupparticipant',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_user_per_group'),
        ),
        migrations.AddConstraint(
            model_name='herogroupparticipant',
            constraint=models.UniqueConstraint(fields=('group', 'character'), name='unique_character_per_group'),
        ),
    ]
