# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_group_invitations_and_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herogroupinvitation',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Offen'),
                    ('accepted', 'Angenommen'),
                    ('rejected', 'Abgelehnt'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
