# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_herogroupinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='characters/portraits/'),
        ),
    ]
