# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_character_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='herogroup',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='groups/portraits/'),
        ),
    ]
