# Generated by Django 6.0 on 2026-05-25 17:39

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_herogroup_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.character_portrait_upload_to),
        ),
        migrations.AlterField(
            model_name='herogroup',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.group_portrait_upload_to),
        ),
    ]
