# Generated by Django 6.0 on 2026-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_character_portrait_alter_herogroup_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.CharField(default='', max_length=120),
        ),
    ]
